# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: Mirror to GitHub

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: swellaby.mirror-git-repository.mirror-git-repository-vsts-task.mirror-git-repository-vsts-task@1
  displayName: 'Mirror Git Repository'
  inputs:
    sourceGitRepositoryUri: 'https://dev.azure.com/martin/AADWebApp/_git/AADWebApp'
    sourceGitRepositoryPersonalAccessToken: '$(ADO-PAT)'
    sourceVerifySSLCertificate: false
    destinationGitRepositoryUri: 'https://github.com/Anthophila/martin_AADWebApp.git'
    destinationGitRepositoryPersonalAccessToken: '$(GH-PAT)'

